name: progetti
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^13.0.1
  connectivity_plus: ^6.0.2
  permission_handler: ^11.0.1
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.6
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  provider: ^6.1.2
  cloud_firestore: ^5.4.2
  intl: ^0.19.0  # Aggiornato
  google_sign_in: ^6.1.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_spinkit: ^5.2.1
  confetti: ^0.7.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.14.1  # Aggiungi questa linea

flutter:
  assets:
    - .env
    -  assets/icons/logo.png

  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/1024.png"
  adaptive_icon_background: "#FFFFFF"  # Può essere un colore o un'immagine
  adaptive_icon_foreground: "assets/icons/1024.png"
  remove_alpha_ios: true
