// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsfde6avxZCAeiPqqLgnh7nqn1n9TTHbk',
    appId: '1:563477959801:web:3ff90c62c82adaed2030a8',
    messagingSenderId: '563477959801',
    projectId: 'aidho-71d57',
    authDomain: 'aidho-71d57.firebaseapp.com',
    databaseURL: 'https://aidho-71d57-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aidho-71d57.appspot.com',
    measurementId: 'G-1XVPZ5KJ1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgRiDLN5Qz_SLTY4NJjcsMGMJmfsGtVrY',
    appId: '1:563477959801:android:b0bec75a6b386c1c2030a8',
    messagingSenderId: '563477959801',
    projectId: 'aidho-71d57',
    databaseURL: 'https://aidho-71d57-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aidho-71d57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABpsRcnVYd3IEtvYqvUY2egHiepT3GYJU',
    appId: '1:563477959801:ios:ab41ef7ee7a74b352030a8',
    messagingSenderId: '563477959801',
    projectId: 'aidho-71d57',
    databaseURL: 'https://aidho-71d57-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aidho-71d57.appspot.com',
    iosBundleId: 'com.example.progetti',
  );
}
